# Generated by Django 3.2.5 on 2021-08-30 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recom_app', '0002_searchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
